# Language options
language: node_js
node_js:
- '0.10'
after_success:
- npm run release

# Auto releasing After success
deploy:
  provider: releases
  api_key:
    secure: aSY1mI9mmzbZCvXFIZpplLSgV7YfGgTDpn4jAGdTfeKNGgaollBqelXKFMbo0UFYI8NJ5R4+NvfbSID5X29wpr2TyQgUSoAII7Xt0Anm0WJn1RkguJBQ83gWpnfTk7FbHXEkGEA/2uPe/6Tu9aMKe3/8b9M5fGjfx9p4ft/agu4=
  file:
    - ../releases/v0.24.0/darwin-x64.zip
    - ../releases/v0.24.0/win32-ia32.zip
  on:
    repo: 59naga/edgy-comment-viewer
    tags: true
    all_branches: true
  skip_cleanup: true