#!/usr/bin/env node

if(typeof require('module')._extensions['.coffee']==='undefined'){
  // Avoid conflicts with another version
  require('coffee-script/register');
}
var app= require(__filename+'.coffee');

app.boot(process.argv);

module.exports= app;